ix(chat): home page add delete button to custom app, remove short description from card view (Issue #2279, #2334)
epam/ai-dial-chat pull request #2391
Opened 2024-10-17 17:36 UTC by Derikyan

**Description:**

Add Delete button on application view for custom app on Home page
On marketplace on card view of All Applications and My Applications should be visible only short description

Issues:

- Issue #2279 
- Issue #2334 

**Checklist:**

- [ ] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [ ] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-10-17 17:36 UTC, ai-dial-actions commented
Hey there and thank you for opening this pull request! 👋🏼

We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

Details:

```
Unknown release type "ix" found in pull request title "ix(chat): home page add delete button to custom app, remove short description from card view (Issue #2279, #2334)". 

Available types:
 - fix
 - hotfix
 - feat
 - feature
 - chore
```
<!-- Sticky Pull Request Commentpr-title-lint-error -->

2024-10-17 17:40 UTC, Derikyan commented
/deploy-review

2024-10-17 19:45 UTC, IlyaBondar requested changes
Divider for short description is not "\n"

2024-10-17 20:22 UTC, Derikyan commented
/deploy-review

2024-10-17 21:32 UTC, IlyaBondar commented on apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
> +          {(isMyAppsTab || (!isMyAppsTab && isMyApp)) && (
```suggestion
          {(isMyAppsTab || isMyApp) && (
```

2024-10-17 21:32 UTC, IlyaBondar commented on apps/chat/src/utils/app/application.ts
> +  getDescription(entity, true);
```suggestion
export const getModelDescription = (entity: DialAIEntityModel) => {
  return entity.description
    ? entity.description.split(QUICK_APP_CONFIG_DIVIDER)[0]
    : '';

export const getModelShortDescription = (entity: DialAIEntityModel) =>
  getModelDescription(entity).split(DESCRIPTION_DELIMITER_REGEX)[0];
```

2024-10-18 07:51 UTC, Derikyan commented
/deploy-review

2024-10-18 08:41 UTC, Derikyan commented
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2391.nightly-test.deltixhub.io
>E2E tests status: success

2024-10-18 09:29 UTC, IlyaBondar approved these changes

2024-10-18 09:30 UTC, merged