feat(chat-e2e): publish folder tests
epam/ai-dial-chat pull request #2597
Opened 2024-11-13 16:36 UTC by irinakartun

**Description:**

publish folder tests

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-11-13 16:39 UTC, irinakartun commented
/deploy-review

2024-11-14 07:50 UTC, irinakartun commented
/deploy-review

2024-11-15 08:29 UTC, irinakartun commented
/deploy-review

2024-11-15 15:18 UTC, irinakartun commented
/deploy-review

2024-11-19 09:08 UTC, irinakartun commented
/deploy-review

2024-11-19 13:40 UTC, nartovm requested changes

2024-11-19 13:40 UTC, nartovm commented on apps/chat-e2e/src/core/dialAdminFixtures.ts
> +    const adminC = adminChat.getChatMessages();
why not const adminChatMessages?

2024-11-19 13:40 UTC, nartovm commented on apps/chat-e2e/src/tests/cleanup.ts
> +      if (requestDetails.resources.some((r) => r.action === 'DELETE')) {
I think we should avoid using double filtering - first by name and then by action. We should consider a request with "publicationRequestPrefix" as having an action of "add" and so on.

```
   for (const publicationRequest of publicationRequests.publications) { // Removed the filter here
      const requestDetails =
        await adminPublicationApiHelper.getPublicationRequestDetails(
          publicationRequest.url,
        );

      if (requestDetails.resources.some((r) => r.action === 'DELETE')) {
        await adminPublicationApiHelper.approveRequest(publicationRequest);
      } else if (requestDetails.resources.some((r) => r.action === 'ADD')) {
        await adminPublicationApiHelper.rejectRequest(publicationRequest);
      }
    }
```

2024-11-19 13:57 UTC, irinakartun commented
/deploy-review

2024-11-19 14:07 UTC, irinakartun commented on apps/chat-e2e/src/tests/cleanup.ts
> +      if (requestDetails.resources.some((r) => r.action === 'DELETE')) {
fixed

2024-11-19 14:07 UTC, irinakartun commented on apps/chat-e2e/src/core/dialAdminFixtures.ts
> +    const adminC = adminChat.getChatMessages();
fixed

2024-11-19 14:12 UTC, irinakartun commented
/deploy-review

2024-11-19 14:34 UTC, irinakartun commented
/deploy-review

2024-11-19 21:07 UTC, nartovm submitted a review, later dismissed

2024-11-19 21:07 UTC, nartovm commented
/deploy-review

2024-11-20 08:32 UTC, irinakartun commented
/deploy-review

2024-11-20 09:17 UTC, nartovm approved these changes

2024-11-20 09:26 UTC, merged