feat(chat): implement apps editor on separated route (Issue #3146)
epam/ai-dial-chat pull request #2669
Opened 2024-11-26 11:55 UTC by valerydluski

**Description:**

implement apps editor on separated route

Issues:

- Issue #3146

**UI changes**

![image](https://github.com/user-attachments/assets/1ca94847-d559-4abf-bf90-8dadb8e7120a)

**Checklist:**

- [x] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [x] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [x] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-11-26 11:55 UTC, ai-dial-actions commented
Hey there and thank you for opening this pull request! 👋🏼

We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

Details:

```
No release type found in pull request title "Feat/apps editor route". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/

Available types:
 - fix
 - hotfix
 - feat
 - feature
 - chore
```
<!-- Sticky Pull Request Commentpr-title-lint-error -->

2024-12-05 14:38 UTC, dspashynskyi commented
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/544721)

2024-12-05 14:50 UTC, valerydluski commented
/deploy-review

2024-12-16 15:22 UTC, irinakartun submitted a review, later dismissed

2025-02-05 12:46 UTC, Alexander-Kezik commented on .gitignore
> +/apps/chat-e2e/.env.development
Do we need to ignore it `.dev`?

2025-02-05 15:07 UTC, valerydluski commented on .gitignore
> +/apps/chat-e2e/.env.development
I'm not sure, but I think it's useful to have all files that might contain secrets in .gitignore.

2025-02-06 16:22 UTC, IlyaBondar commented on .gitignore
> +/apps/chat-e2e/.env.development
@valerydluski , we shouldn't save any secrets into `.env.development`. Only in `.env.local`. Please remove this line

2025-02-06 16:23 UTC, IlyaBondar commented on .github/workflows/pr.yml
> +    branches: [development, release-*, feat/marketplace]
revert it, please

2025-02-06 16:27 UTC, IlyaBondar commented on apps/chat-e2e/src/tests/abortedReplay.test.ts
> +dialTest.skip(
all skiped e2e tests should be reviewed and fixed by @irinakartun and @nartovm before merging into `development`

2025-02-10 19:12 UTC, IlyaBondar commented on apps/chat/src/utils/app/application-type-schema.ts
> +export function encrypt(text: string) {
```suggestion
export function encode(text: string) {
```

2025-02-10 19:12 UTC, IlyaBondar commented on apps/chat/src/utils/app/application-type-schema.ts
> +export function decrypt(encryptedText: string) {
```suggestion
export function decode(encodedText: string) {
```

2025-02-10 19:12 UTC, IlyaBondar commented on apps/chat/src/utils/app/application.ts
> +  }
```suggestion
    return {
      ...commonData,
      application_properties: applicationData.applicationProperties ?? null,
      application_type_schema_id:
        applicationData.applicationTypeSchemaId ?? schema['$id'],
    };
  }
```

2025-02-10 19:12 UTC, IlyaBondar commented on apps/chat/src/utils/app/application.ts
> +    applicationProperties: application.application_properties,
`document_relative_url` should be decoded
```suggestion
    applicationProperties: mapApplicationPropertiesFromApi(
      application.application_properties,
    ),
```

2025-02-11 01:41 UTC, IlyaBondar requested changes

2025-02-11 01:41 UTC, IlyaBondar commented on Dockerfile
> -FROM node:22-alpine AS base
revert this file

2025-02-11 01:41 UTC, IlyaBondar commented on apps/chat/public/locales/en/sidebar.json
> -    "share.modal.link_conversation": "This conversation and future changes to it will be visible to users who follow the link. Only owner will be able to make changes.",
revert this file

2025-02-11 01:41 UTC, IlyaBondar commented on package.json
> -  "version": "0.25.0-rc",
revert all changes here except `@types/json-schema` and `cross-spawn`

2025-02-11 01:41 UTC, IlyaBondar commented on package-lock.json
> -  "version": "0.25.0-rc",
regenerate this file after reverting `package.json` (`npm i && npm ddp`)

2025-02-11 01:43 UTC, IlyaBondar commented on apps/overlay-sandbox/app/cases/components/chatOverlayWrapper.tsx
> -        <details open={true} id="chat-actions">
revert this file

2025-02-11 01:45 UTC, IlyaBondar commented on apps/chat-e2e/src/assertions/api/apiAssertion.ts
> -  public async assertMoveRequest(
revert all e2e-test changes

2025-02-11 01:47 UTC, IlyaBondar commented on apps/chat/public/images/icons/insert-prompt.svg
revert this file back

2025-02-11 10:52 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +  const tabs = [
lets move this var out of the component

2025-02-11 11:03 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
> +export const getPreviewEntityData = (data: ApplicationGeneralInfoFormData) => {
maybe lets move this to some utils file? And give it a `getApplicationEntityFields` name or something like that?

2025-02-11 11:04 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
> +            onPublish={() => null}
you can move `() => null` out of the component and name it like `fakeCallback`

2025-02-11 11:09 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
> +  if (type === 'code-app') {
Time to introduce ApplicationType enum?

2025-02-11 11:16 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
> +              getItemLabel={(i: unknown) => i as string}
maybe we can move the `(var: unknown) => var as string` to some util.

2025-02-11 11:17 UTC, Alexander-Kezik commented on apps/chat/src/components/Chat/ModelList.tsx
>      [dispatch, handleOpenApplicationModal],
fix warning

2025-02-11 11:18 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
> +                setConfirmSharingRevoke(undefined);
it won't be closed on 'cancel' button. Just swap 325 and 326 lines

2025-02-11 11:30 UTC, Alexander-Kezik commented on apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
> +          setConfirmSharingRevoke({
guess if you will confirm this
`if` statement will work again and you will see the confirmation again

2025-02-11 12:35 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +  const tabs = [
must be wrapped into `useMemo`

2025-02-11 12:37 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
> +            oldApplicationId: data.id,
![image](https://github.com/user-attachments/assets/7133c984-e261-4c0d-918d-4a06558eed9f)

2025-02-11 15:17 UTC, valerydluski commented
/deploy-review

2025-02-11 15:17 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
> +            oldApplicationId: data.id,
fixed

2025-02-11 16:22 UTC, denys-kolomiitsev commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +              onClick={() => setMenuOpen(!menuOpen)}
Updating state like this could lead to unexpected state updates and bugs, because "!menuOpen" may refer to an outdated state value by the time it's actually applied. It is better to use a functional update to guarantee that you receive the most recent state value at the time of the update.
```suggestion
              onClick={() => setMenuOpen((prevState)=> !prevState)}
```

2025-02-11 18:00 UTC, IlyaBondar reviewed
context menu in preview is clickable and show error for `Share`
![image](https://github.com/user-attachments/assets/15047519-1bc8-4090-a7f1-1a6f9b7e3742)
there shouldn't be `bookmark` icon for created app
![image](https://github.com/user-attachments/assets/1fba4c04-927a-4d37-8304-52d8c2a6dc4b)

2025-02-11 20:58 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +  const router = useRouter();
1. it would be nice to make deconstruction once and use everywhere
2. it's better to use `reference` instead of `id`. Reference isn't changed during application life

```tsx
const { id = '', slug = '' } = router.query;
```

2025-02-11 20:58 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +export enum TabKeys {
if it's used only here `export` can be remove. In other case it's better to move it in constants or types

2025-02-11 20:58 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +  const router = useRouter();
UPD: why we can pass `const query = router.query` into both `href`?
```tsx
        href: {
          pathname: `/apps-editor/[slug]`,
          query,
        },
```

2025-02-11 21:10 UTC, IlyaBondar commented on apps/chat/src/store/application-type-schemas/application-type-schemas.epic.ts
use camelCase for file names of selectors, epics, reducers, please

2025-02-11 21:10 UTC, IlyaBondar commented on apps/chat/src/store/application-type-schemas/application-type-schemas.reducer.ts
> +  selectedSchema: undefined,
do you use `selectedSchema` and `schemaDetailsLoading` anywhere?

2025-02-11 21:11 UTC, IlyaBondar commented on apps/chat/src/store/application-type-schemas/application-type-schemas.selectors.ts
> +);
`createSelector` doesn't make sense here
```suggestion
export const selectAllSchemas = (state: RootState) =>
  rootSelector(state).schemas;
```

2025-02-11 21:28 UTC, IlyaBondar commented on apps/chat/src/utils/app/route.ts
> +      return PageType.AppsEditorSettings;
```suggestion
    case '/apps-editor/[slug]/settings':
      return PageType.AppsEditorSettings;
```

2025-02-11 21:28 UTC, IlyaBondar commented on apps/chat/src/utils/app/file.ts
> +  return path.startsWith('api') ? path.replace('api/', '/api/') : path;
```suggestion
  return path.startsWith('api/') ? path.replace('api/', '/api/') : path;
```

2025-02-11 21:28 UTC, IlyaBondar commented on apps/chat/src/utils/app/data/application-type-schemas-service.ts
> +  public static getApplicationTypeSchema(id: string): Observable<any> {
<img width="479" alt="image" src="https://github.com/user-attachments/assets/6c98dd69-a3a6-4c2c-8202-0102f07df5b2" />

2025-02-11 21:28 UTC, IlyaBondar commented on apps/chat/src/utils/app/data/application-type-schemas-service.ts
> +      catchError(() => of([])),
need to handle error. At least add TODO to do it in future

2025-02-11 21:28 UTC, IlyaBondar commented on apps/chat/src/components/Marketplace/ApplicationCard.tsx
>          onClick: handleOpenSharing,
add `!isPreview` condition into `handleOpenSharing` to not open Share dialog

2025-02-11 21:41 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
> +        <div className="w-full max-w-[700px] flex-col divide-y divide-tertiary bg-blackout bg-layer-3 p-3 md:p-5 xl:max-w-[720px]">
<img width="573" alt="image" src="https://github.com/user-attachments/assets/4070a59e-9a11-4b8a-89d7-ded03e429441" />

2025-02-11 21:41 UTC, IlyaBondar commented on apps/chat/src/components/Marketplace/ApplicationCard.tsx
>          onClick: handleOpenSharing,
UPD: and `&& !isPreview` for bookmark (line 340)

2025-02-11 22:36 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +import LogOutIcon from '../../../public/images/icons/log-out.svg';
```suggestion
import LogOutIcon from '@/public/images/icons/log-out.svg';
```

2025-02-11 22:38 UTC, IlyaBondar commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +            Add application
I suppose we need to specify which type of application is creating and maybe change `Add` and `Edit` verbs depends on mode

2025-02-12 16:02 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
> +export const getPreviewEntityData = (data: ApplicationGeneralInfoFormData) => {
done

2025-02-12 16:02 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
> +            onPublish={() => null}
done

2025-02-12 16:02 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
> +  if (type === 'code-app') {
done

2025-02-12 16:02 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
> +              getItemLabel={(i: unknown) => i as string}
done

2025-02-12 16:02 UTC, valerydluski commented on apps/chat/src/components/Chat/ModelList.tsx
>      [dispatch, handleOpenApplicationModal],
fixed

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +export enum TabKeys {
removed

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/store/application-type-schemas/application-type-schemas.epic.ts
done

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/store/application-type-schemas/application-type-schemas.reducer.ts
> +  selectedSchema: undefined,
removed

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/store/application-type-schemas/application-type-schemas.selectors.ts
> +);
done

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/utils/app/route.ts
> +      return PageType.AppsEditorSettings;
updated

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/utils/app/file.ts
> +  return path.startsWith('api') ? path.replace('api/', '/api/') : path;
fixed

2025-02-12 16:03 UTC, valerydluski commented on apps/chat/src/utils/app/data/application-type-schemas-service.ts
> +  public static getApplicationTypeSchema(id: string): Observable<any> {
done

2025-02-12 16:04 UTC, valerydluski commented on apps/chat/src/utils/app/data/application-type-schemas-service.ts
> +      catchError(() => of([])),
added comment

2025-02-12 16:04 UTC, valerydluski commented on apps/chat/src/components/Marketplace/ApplicationCard.tsx
>          onClick: handleOpenSharing,
done

2025-02-12 16:04 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
> +        <div className="w-full max-w-[700px] flex-col divide-y divide-tertiary bg-blackout bg-layer-3 p-3 md:p-5 xl:max-w-[720px]">
done

2025-02-12 16:04 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +import LogOutIcon from '../../../public/images/icons/log-out.svg';
fixed

2025-02-12 16:21 UTC, valerydluski commented
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2669.nightly-test.deltixhub.io
>E2E tests status: failed

2025-02-12 16:28 UTC, Alexander-Kezik commented on apps/chat/src/components/IframeRenderer/index.tsx
> +        });
Should we destroy if props have changed to avoid memory leak?
```suggestion
        if (visualizer.current) {
          visualizer.current.destroy();
        }
    
        visualizer.current = new VisualizerConnector(containerRef.current, {
          domain: iframeUrl,
          hostDomain: window.location.origin,
          visualizerName: title,
        });
```

2025-02-13 09:33 UTC, irinakartun commented
/deploy-review

2025-02-13 12:33 UTC, Gimir requested changes

2025-02-13 12:33 UTC, Gimir commented on apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
> +      : `files/${bucket}/appdata`,
Source folder should be empty as default. We have 'examples' if we don't have files in the selected directory. If we click on some example application now, we will create these files in the /appdata directory which is not supposed to be used that way.

2025-02-13 12:33 UTC, Gimir commented on apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
> +      getNextDefaultName(DEFAULT_APPLICATION_NAME, models ?? [], 0, true),
Need to dispatch getModels on page load, otherwise we will get error on trying to create an application with default name if we open apps-editor page without navigating to it from marketplace

<img width="885" alt="Снимок экрана 2025-02-13 в 15 15 42" src="https://github.com/user-attachments/assets/c4896511-3cf3-4c4a-86d5-5e92dd43f484" />

2025-02-13 14:41 UTC, Gimir requested changes

2025-02-13 14:41 UTC, Gimir commented on apps/chat/src/components/AppsEditor/Settings/index.tsx
> +      ['Quick App']: getQuickAppDefaultValues({
Quick app settings tab does not open and show infinite loader instead.
When quick app editor open **type** is equals to 'QuickApps', not 'Quick App'. Same for line 130. 
It's better to map this to ApplicationType enum here also.

2025-02-18 13:08 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
> +      getNextDefaultName(DEFAULT_APPLICATION_NAME, models ?? [], 0, true),
fixed

2025-02-18 13:26 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +            Add application
fixed

2025-02-18 13:27 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
> +      : `files/${bucket}/appdata`,
I updated

2025-02-18 13:28 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/Settings/index.tsx
> +      ['Quick App']: getQuickAppDefaultValues({
This is a temporary solution until Quick App has a custom editor.

2025-02-18 13:29 UTC, valerydluski commented
/deploy-review

2025-02-21 11:52 UTC, valerydluski commented on apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
> +  const router = useRouter();
There was an issue with dynamic routes in Next.js. 
The problem is described in detail here: https://github.com/vercel/next.js/discussions/33243

2025-02-21 11:53 UTC, valerydluski commented on apps/chat/src/components/IframeRenderer/index.tsx
> +        });
done

2025-02-21 12:19 UTC, IlyaBondar commented
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-2669.nightly-test.deltixhub.io
>E2E tests status: failed

2025-02-21 12:44 UTC, valerydluski commented
/deploy-review

2025-02-21 14:07 UTC, Gimir commented on apps/chat/src/utils/app/application.ts
> +      application_properties: applicationData.applicationProperties ?? null,
## Blocker:

URL's in application_properties should be encoded. If set some file with spaces in it's name in document_relative_url there will be an error.
Also if there is no file url in document_relative_url there should be no such field in the final payload, now there is empty string if first set and then remove document_relative_url field.

2025-02-21 14:08 UTC, Gimir commented on apps/chat/src/utils/app/application.ts
> +      application_properties: applicationData.applicationProperties ?? null,
I'm suggesting to reuse previous method mapApplicationPropertiesToApi

2025-02-21 14:12 UTC, irinakartun commented
/deploy-review

2025-02-21 14:33 UTC, valerydluski commented on apps/chat/src/utils/app/application.ts
> +      application_properties: applicationData.applicationProperties ?? null,
@Gimir  I think using a common mapApplicationPropertiesToApi for all application types, which can be numerous and have different schemas, might not be very convenient in the future. I made adjustments here: https://github.com/epam/ai-dial-chat/pull/3212.

If you're okay with this, I'll merge it into the current branch.

2025-02-21 16:11 UTC, IlyaBondar commented
/deploy-review

2025-02-21 17:13 UTC, valerydluski commented
/deploy-review

2025-02-24 11:34 UTC, irinakartun commented
/deploy-review

2025-02-24 11:49 UTC, Gimir approved these changes, later dismissed

2025-02-24 12:48 UTC, IlyaBondar commented
/deploy-review

2025-02-24 15:02 UTC, IlyaBondar commented
/deploy-review

2025-02-24 15:42 UTC, IlyaBondar approved these changes

2025-02-24 15:43 UTC, Gimir approved these changes

2025-02-24 15:46 UTC, irinakartun approved these changes

2025-02-24 16:07 UTC, merged