fix(overlay): hide 'configure settings' when features are disabled (Issue #2728)
epam/ai-dial-chat pull request #2769
Opened 2024-12-10 12:35 UTC by Derikyan

**Description:**

'Configure settings' and 'Change agent' are available in Overlay though all the features are disabled
Seems that EmptyChatSettings = 'empty-chat-settings' doesn't work at all? need to re-check for the whole DIAL

Issues:

- Issue #2728

**UI changes**

<img width="428" alt="Снимок экрана 2024-12-10 в 16 35 32" src="https://github.com/user-attachments/assets/6e3a6405-24e7-4fb8-89c6-db213357f323">

**Checklist:**

- [ ] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [ ] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-12-10 12:36 UTC, Derikyan commented
/deploy-review

2024-12-10 16:53 UTC, IlyaBondar approved these changes

2024-12-10 16:57 UTC, IlyaBondar requested changes

2024-12-10 16:57 UTC, IlyaBondar commented on apps/chat/src/components/Chat/EmptyChatDescription.tsx
> +    SettingsSelectors.selectEnabledFeatures,
we can use `isFeatureEnabled` instead

2024-12-10 16:57 UTC, IlyaBondar commented on apps/chat/src/components/Chat/EmptyChatDescription.tsx
> +  );
```suggestion
  const isExternal = isEntityIdExternal(conversation);
```

2024-12-11 05:23 UTC, Derikyan commented
/deploy-review

2024-12-11 14:24 UTC, nartovm commented
/deploy-review

2024-12-11 14:44 UTC, irinakartun submitted a review, later dismissed

2024-12-11 15:10 UTC, irinakartun approved these changes

2024-12-11 15:24 UTC, IlyaBondar approved these changes

2024-12-11 19:47 UTC, merged