fix(chat): increase max headers size (Issue #2852)
epam/ai-dial-chat pull request #2871
Opened 2024-12-24 15:22 UTC by Alexander-Kezik

**Description:**

increase max headers size

Issues:

- Issue #2852

**Checklist:**

- [ ] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [ ] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-12-24 17:15 UTC, denys-kolomiitsev submitted a review, later dismissed

2024-12-26 13:35 UTC, IlyaBondar approved these changes, later dismissed

2024-12-26 13:38 UTC, IlyaBondar commented
/deploy-review

2024-12-26 13:41 UTC, IlyaBondar commented on apps/chat/README.md
> +| `MAX_HTTP_HEADERS_SIZE`                   |    No    | Defines the maximum size of headers for Next.js server. <br />**Note**: this variable is used only when running a `dockerfile`.
Need to check that for our environments (local, Review, Staging) also is used default limit with 32 KB

2025-01-04 01:01 UTC, justrp commented on startup.sh
> +export NODE_OPTIONS="--max-http-header-size=$MAX_HTTP_HEADERS_SIZE"
```suggestion
export NODE_OPTIONS="--max-http-header-size=$MAX_HTTP_HEADERS_SIZE ${NODE_OPTIONS}"
```

I could easily imagine someone's passing this environment variable as part of their infrastructure configuration. It would be very hard to figure out why it does not work as expected because here we override it's value.

2025-01-04 04:39 UTC, Derikyan commented
/deploy-review

2025-01-20 15:22 UTC, IlyaBondar approved these changes, later dismissed

2025-01-21 15:45 UTC, IlyaBondar requested changes

2025-01-21 15:45 UTC, IlyaBondar commented on .dockerignore
> +docs
why did you add `docs` here?

2025-01-21 15:45 UTC, IlyaBondar commented on apps/chat/README.md
> +1. Install project dependencies:
revert numbers for list, please

2025-01-21 17:11 UTC, nepalevov commented on .dockerignore
> +docs
why do we need docs for building the container image?

2025-01-22 13:48 UTC, IlyaBondar approved these changes, later dismissed

2025-01-22 14:02 UTC, IlyaBondar approved these changes

2025-01-22 14:14 UTC, merged