fix(chat): improve Change Agent handling and add mobile tooltips in chats (Issues #2842, #2849)
epam/ai-dial-chat pull request #2892
Opened 2024-12-30 15:50 UTC by Derikyan

**Description:**

In mobile device is proper tooltip on model icon click (ok), but there is no tooltip on conversation setting (need to be implemented)
If new conversation is on the screen, user has never clicked on 'Change agent' link, we should open Change agent screen on + button click

Issues:

- Issue #2842 
- Issue #2849 

**Checklist:**

- [ ] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [ ] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-12-30 15:52 UTC, Derikyan commented
/deploy-review

2024-12-30 16:47 UTC, IlyaBondar requested changes

2024-12-30 16:47 UTC, IlyaBondar commented on apps/chat/src/store/conversations/conversations.epics.ts
> +              return of(
there **shouldn't** be `return`. It should be concatted with other actions

2024-12-30 18:07 UTC, Derikyan commented
/deploy-review

2024-12-30 19:10 UTC, IlyaBondar approved these changes

2024-12-31 12:47 UTC, IlyaBondar requested changes
E2E-tests should be fixed before merge

2025-01-07 18:38 UTC, IlyaBondar commented
/deploy-review

2025-01-08 08:40 UTC, irinakartun commented
/deploy-review

2025-01-08 09:54 UTC, IlyaBondar approved these changes

2025-01-08 09:55 UTC, irinakartun approved these changes

2025-01-08 09:56 UTC, merged