feat(chat): add possibility to preview shared prompt (Issue #743)
epam/ai-dial-chat pull request #806
Opened 2024-02-20 13:49 UTC by Alexander-Kezik

- Issue: https://github.com/epam/ai-dial-chat/issues/743

2024-02-20 18:44 UTC, Alexander-Kezik commented
/deploy-review

2024-02-20 21:29 UTC, IlyaBondar requested changes

2024-02-20 21:29 UTC, IlyaBondar commented on apps/chat/src/components/Common/ItemContextMenu.tsx
> +        onClick: onView,
React Hook useMemo has a missing dependency: 'onView'. Either include it or remove the dependency array

2024-02-20 21:36 UTC, IlyaBondar commented on apps/chat/src/components/Promptbar/components/PromptModal.tsx
> +              className={classNames(inputClassName)}
I suppose we can remove `classNames` here

2024-02-20 21:36 UTC, IlyaBondar commented on apps/chat/src/components/Promptbar/components/PromptModal.tsx
> +      heading={`${t('Edit prompt')}: ${name}`}
Dio we really need it? `name` is empty initially

2024-02-20 21:36 UTC, IlyaBondar commented on apps/chat/src/components/Promptbar/components/PromptModal.tsx
> +          <div className={'flex justify-end'}>
revert it

2024-02-20 21:51 UTC, IlyaBondar approved these changes, later dismissed

2024-02-20 21:51 UTC, IlyaBondar commented
/deploy-review

2024-02-20 22:00 UTC, IlyaBondar commented on apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
> +                <IconTrashX size={24} strokeWidth="1.5" />
need to add tooltips for these two buttons

2024-02-21 08:23 UTC, IlyaBondar approved these changes

2024-02-21 08:28 UTC, Alexander-Kezik commented
/deploy-review

2024-02-21 08:51 UTC, merged