fix(chat): removes sidebar delete and import buttons if only shared items exist (Issue #750)
epam/ai-dial-chat pull request #886
Opened 2024-02-29 16:12 UTC by Alexander-Kezik

**Description:**

 Removes sidebar delete and import buttons if only shared items exist.

Issues:

- Issue: https://github.com/epam/ai-dial-chat/issues/750

**Checklist:**

- [ ] the pull request name complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] the pull request name starts with `fix(<scope>):`, `feat(<scope>):`, `feature(<scope>):`, `chore(<scope>):`, `hotfix(<scope>):` or `e2e(<scope>):`. If contains breaking changes then the pull request name must start with `fix(<scope>)!:`, `feat(<scope>)!:`, `feature(<scope>)!:`, `chore(<scope>)!:`, `hotfix(<scope>)!:` or `e2e(<scope>)!:` where `<scope>` is name of affected project: `chat`, `chat-e2e`, `overlay`, `shared`, `sandbox-overlay`, etc.
- [ ] the pull request name ends with `(Issue #<TICKET_ID>)` (comma-separated list of issues)
- [ ] I confirm that do not share any confidential information like API keys or any other secrets and private URLs

2024-02-29 17:43 UTC, IlyaBondar requested changes

2024-02-29 17:43 UTC, IlyaBondar commented on apps/chat/src/store/conversations/conversations.selectors.ts
> +);
Why do we do all this check on UI?
Let's memorise it in selector `selectDoesAnyMyItemExists` which returns boolean instead
```suggestion
export const selectDoesAnyMyItemExist = createSelector(
  [selectFolders, selectConversations],
  (folders, conversations) => {
    const conversationRootId = getConversationRootId();
    return (
      conversations.some((conv) => conv.id.startsWith(conversationRootId)) ||
      folders.some((folder) => folder.id.startsWith(conversationRootId))
    );
  },
);
```

2024-02-29 17:43 UTC, IlyaBondar commented on apps/chat/src/store/prompts/prompts.selectors.ts
> +
Why do we do all this check on UI?
Let's memorise it in selector `selectDoesAnyMyItemExists` which returns boolean instead
```suggestion
export const selectDoesAnyMyItemExist = createSelector(
  [selectFolders, selectPrompts],
  (folders, prompts) => {
    const conversationRootId = getPromptRootId();
    return (
      prompts.some((prompt) => prompt.id.startsWith(conversationRootId)) ||
      folders.some((folder) => folder.id.startsWith(conversationRootId))
    );
  },
);
```

2024-03-01 00:25 UTC, Alexander-Kezik commented
/deploy-review

2024-03-01 08:01 UTC, Alexander-Kezik commented
/deploy-review
>Environment URL: https://chat-ai-dial-chat-pr-886.nightly-test.deltixhub.io
>E2E tests status: success

2024-03-01 09:08 UTC, IlyaBondar approved these changes

2024-03-01 09:49 UTC, merged